services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=markets'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - '5016:80'
    user: "$UID:$GID"
    environment:
      - PGADMIN_DEFAULT_EMAIL=demo@demo.com
      - PGADMIN_DEFAULT_PASSWORD=password
#    volumes:
#      - ./pgadmin-data:/var/lib/pgadmin